# Generated by Django 3.0.8 on 2023-02-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='obtenu_webscraping',
            field=models.BooleanField(default=False),
        ),
    ]
