# Generated by Django 3.0.8 on 2023-02-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageoffre', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
